from .. import infos
from . import services
from . import devices
from .decorators import info

@info(infos.clients.Web)
class Web(devices.WebClient, services.YouTubeClient): ...

@info(infos.clients.WebMusic)
class WebMusic(devices.WebClient, services.YouTubeMusicClient): ...

@info(infos.clients.WebKids)
class WebKids(devices.WebClient, services.YouTubeKidsClient): ...

@info(infos.clients.WebStudio)
class WebStudio(devices.WebClient, services.YouTubeStudioClient): ...

@info(infos.clients.Android)
class Android(devices.AndroidClient, services.YouTubeClient): ...

@info(infos.clients.AndroidMusic)
class AndroidMusic(devices.AndroidClient, services.YouTubeMusicClient): ...

@info(infos.clients.AndroidKids)
class AndroidKids(devices.AndroidClient, services.YouTubeKidsClient): ...

@info(infos.clients.AndroidStudio)
class AndroidStudio(devices.AndroidClient, services.YouTubeStudioClient): ...

@info(infos.clients.Ios)
class Ios(devices.IosClient, services.YouTubeClient): ...

@info(infos.clients.IosMusic)
class IosMusic(devices.IosClient, services.YouTubeMusicClient): ...

@info(infos.clients.IosKids)
class IosKids(devices.IosClient, services.YouTubeKidsClient): ...

@info(infos.clients.IosStudio)
class IosStudio(devices.IosClient, services.YouTubeStudioClient): ...

@info(infos.clients.Tv)
class Tv(devices.TvClient, services.YouTubeClient): ...
