from typing import Dict, List

from .models import Client, Context, Platform, Service

services: Dict[str, Service] = dict(
    youtube=Service(
        url="https://www.youtube.com/",
    ),
    youtube_music=Service(
        url="https://music.youtube.com/",
    ),
    youtube_kids=Service(
        url="https://www.youtubekids.com/",
    ),
    youtube_studio=Service(
        url="https://studio.youtube.com/",
    ),
)

platforms: Dict[str, Platform] = dict(
    web=Platform(
        user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36",
    ),
    android=Platform(
        user_agent="Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Mobile Safari/537.36",
    ),
    ios=Platform(
        user_agent="Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/98.2  Mobile/15E148 Safari/605.1.15",
    ),
    tv=Platform(
        user_agent="Mozilla/5.0 (PlayStation 4 5.55) AppleWebKit/601.2 (KHTML, like Gecko)",
    ),
)

contexts: List[Context] = [
    Context(
        client=Client(
            name="MWEB",
            version="2.20211214.00.00",
            key="AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8",
        ),
        platform=platforms["web"],
        service=services["youtube"],
    ),
    Context(
        client=Client(
            name="WEB",
            version="2.20210223.09.00",
            key="AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8",
        ),
        platform=platforms["web"],
        service=services["youtube"],
    ),
    Context(
        client=Client(
            name="WEB_REMIX",
            version="0.1",
            key="AIzaSyC9XL3ZjWddXya6X74dJoCTL-WEYFDNX30",
        ),
        platform=platforms["web"],
        service=services["youtube_music"],
    ),
    Context(
        client=Client(
            name="WEB_KIDS",
            version="2.20220414.00.00",
            key="AIzaSyBbZV_fZ3an51sF-mvs5w37OqqbsTOzwtU",
        ),
        platform=platforms["web"],
        service=services["youtube_kids"],
    ),
    Context(
        client=Client(
            name="WEB_CREATOR",
            version="1.20210223.01.00",
            key="AIzaSyBUPetSUmoZL-OhlxA7wSac5XinrygCqMo",
        ),
        platform=platforms["web"],
        service=services["youtube_studio"],
    ),
    Context(
        client=Client(
            name="WEB_EMBEDDED_PLAYER",
            version="1.20220413.01.00",
            key="AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8",
        ),
        platform=platforms["web"],
        service=services["youtube"],
    ),
    Context(
        client=Client(
            name="ANDROID",
            version="16.07.34",
            key="AIzaSyA8eiZmM1FaDVjRy-df2KTyQ_vz_yYM39w",
        ),
        platform=platforms["android"],
        service=services["youtube"],
    ),
    Context(
        client=Client(
            name="ANDROID_MUSIC",
            version="4.16.51",
            key="AIzaSyAOghZGza2MQSZkY_zfZ370N-PUdXEo8AI",
        ),
        platform=platforms["android"],
        service=services["youtube_music"],
    ),
    Context(
        client=Client(
            name="ANDROID_KIDS",
            version="6.02.3",
            key="AIzaSyAxxQKWYcEX8jHlflLt2Qcbb-rlolzBhhk",
        ),
        platform=platforms["android"],
        service=services["youtube_kids"],
    ),
    Context(
        client=Client(
            name="ANDROID_CREATOR",
            version="21.06.103",
            key="AIzaSyD_qjV8zaaUMehtLkrKFgVeSX_Iqbtyws8",
        ),
        platform=platforms["android"],
        service=services["youtube_studio"],
    ),
    Context(
        client=Client(
            name="ANDROID_EMBEDDED_PLAYER",
            version="16.20",
            key="AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8",
        ),
        platform=platforms["android"],
        service=services["youtube"],
    ),
    Context(
        client=Client(
            name="IOS",
            version="17.14.2",
            key="AIzaSyB-63vPrdThhKuerbB2N_l7Kwwcxj6yUAc",
        ),
        platform=platforms["ios"],
        service=services["youtube"],
    ),
    Context(
        client=Client(
            name="IOS_MUSIC",
            version="4.16.1",
            key="AIzaSyBAETezhkwP0ZWA02RsqT1zu78Fpt0bC_s",
        ),
        platform=platforms["ios"],
        service=services["youtube_music"],
    ),
    Context(
        client=Client(
            name="IOS_KIDS",
            version="5.42.2",
            key="AIzaSyA6_JWXwHaVBQnoutCv1-GvV97-rJ949Bc",
        ),
        platform=platforms["ios"],
        service=services["youtube_kids"],
    ),
    Context(
        client=Client(
            name="IOS_CREATOR",
            version="20.47.100",
            key="AIzaSyAPyF5GfQI-kOa6nZwO8EsNrGdEx9bioNs",
        ),
        platform=platforms["ios"],
        service=services["youtube_studio"],
    ),
    Context(
        client=Client(
            name="IOS_MESSAGES_EXTENSION",
            version="16.20",
            key="AIzaSyDCU8hByM-4DrUqRUYnGn-3llEO78bcxq8",
        ),
        platform=platforms["ios"],
        service=services["youtube"],
    ),
    Context(
        client=Client(
            name="TVHTML5",
            version="7.20210224.00.00",
            key="AIzaSyDCU8hByM-4DrUqRUYnGn-3llEO78bcxq8",
        ),
        platform=platforms["tv"],
        service=services["youtube"],
    ),
]
